spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: QHL20000814.
    url: jdbc:mysql://localhost:3306/java0906?useSSL=false
    hikari:
      minimum-idle: 6
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
